import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Hero from "@/components/hero/Hero";
import { client } from "@/sanity/lib/client";

import "bootstrap/dist/css/bootstrap.min.css";
import "react-tooltip/dist/react-tooltip.css";
import "@/sass/style.scss";
import "./globals.css"
import "swiper/css";
import "swiper/css/autoplay";
import "swiper/css/grid";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "ORGANI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await client.fetch(`*[_type == "category"] {
  _id,
  title,
  "slug": slug.current,
}`);

  const siteSettings = await client.fetch(
    `*[_type == "siteSettings"][0]{email, phone, address, socialHandles}`
  );

  return (
    <ClerkProvider dynamic>
      <Header siteSettings={siteSettings} />
      <Hero phone={siteSettings.phone} categories={categories} />
      {children}
      <Footer siteSettings={siteSettings} />
    </ClerkProvider>
  );
}
